version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile.spring
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/moneytracker_db
      - SPRING_DATASOURCE_USERNAME=me
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_SECRET=684C2F5961577166467076783637326D4E385A754E454A2B4D6F6E772F52376E6931587A3355612B306A55595341504D7774484F6B76782F56615164363047320A
      - JWT_EXPIRATION=86400
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - app-network

  flask-service:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    environment:
      - SPRING_API_URL=http://spring-app:8080/api/transactions/user/{user_id}/spending-by-category
    depends_on:
      - spring-app
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=moneytracker_db
      - MYSQL_USER=me
      - MYSQL_PASSWORD=
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge